# Generated by Django 6.0.5 on 2026-05-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Welcome to the Future of Learning', max_length=100)),
                ('title_line_1', models.CharField(default='Master Future', max_length=100)),
                ('title_line_2_gradient', models.CharField(default='Tech Skills', max_length=100)),
                ('subtitle', models.TextField(default='Affordable, premium-quality courses in cybersecurity, AI, development, and modern technology. Built for the ambitious.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('color_class', models.CharField(default='text-accent-neon', help_text='e.g. text-accent-neon, text-accent-purple, text-accent-cyan', max_length=50)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
