# Generated by Django 6.0.5 on 2026-05-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='highlights',
            field=models.TextField(blank=True, help_text='One per line', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='instructor',
            field=models.CharField(default='Tapeflicker Expert', max_length=150),
        ),
        migrations.AddField(
            model_name='event',
            name='requirements',
            field=models.TextField(blank=True, help_text='One per line', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Webinar', 'Webinar'), ('Workshop', 'Live Workshop'), ('Bootcamp', 'Bootcamp'), ('Hackathon', 'Hackathon'), ('AMA Session', 'AMA Session'), ('AI Session', 'AI Session'), ('Cybersecurity Lab', 'Cybersecurity Live Lab')], default='Webinar', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, help_text='Optional: If blank, falls back to WhatsApp', null=True),
        ),
    ]
