# Generated by Django 6.0.3 on 2026-05-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_highlights_event_instructor_event_requirements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Tapeflicker', max_length=200)),
                ('description', models.TextField(default="We believe that high-quality tech education shouldn't cost a fortune. Tapeflicker is built by developers, for future developers and cybersecurity experts.")),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_text', models.TextField(default='To democratize access to premium tech education through affordable, high-quality courses.')),
                ('vision_title', models.CharField(default='Our Vision', max_length=100)),
                ('vision_text', models.TextField(default='A world where anyone with ambition can learn the skills needed to build the future.')),
                ('values_title', models.CharField(default='Our Values', max_length=100)),
                ('values_text', models.TextField(default='Quality over quantity. Student success above all. Continuous innovation in learning.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
