# Generated by Django 6.0.3 on 2026-06-14 08:24

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.UniqueUploadPath('chat_attachments/'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'rar', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'png', 'jpg', 'jpeg', 'webp', 'mp4', 'avi', 'mov']), courses.models.FileSizeValidator(12)]),
        ),
    ]
