# Generated by Django 6.0.5 on 2026-05-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_current_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Instructor', 'Instructor'), ('Moderator', 'Moderator'), ('Admin', 'Admin')], default='Student', max_length=20),
        ),
    ]
