# Generated by Django 6.0.5 on 2026-06-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_goal',
            field=models.CharField(default='Daily Cybersecurity Lesson', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='learning_rank',
            field=models.CharField(default='Novice', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.IntegerField(default=150),
        ),
    ]
