# Generated by Django 6.0.3 on 2026-05-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_banner_course_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False, help_text="Check this to make the course free. Users won't need to pay."),
        ),
    ]
