# Generated by Django 6.0.3 on 2026-06-14 08:24

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_created_at_lesson_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.UniqueUploadPath('course_banners/'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'gif']), courses.models.FileSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.UniqueUploadPath('course_thumbnails/'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'gif']), courses.models.FileSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.UniqueUploadPath('lesson_resources/'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'rar', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'png', 'jpg', 'jpeg', 'webp', 'mp4', 'avi', 'mov']), courses.models.FileSizeValidator(25)]),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.UniqueUploadPath('lesson_resources/'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'rar', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'png', 'jpg', 'jpeg', 'webp', 'mp4', 'avi', 'mov']), courses.models.FileSizeValidator(25)]),
        ),
    ]
